import mongoose from 'mongoose';

const questionSchema = new mongoose.Schema({
  text: { type: String, required: true },
  options: [{ type: String, required: true }],
  correctIndex: { type: Number, required: true },
});

const quizSchema = new mongoose.Schema(
  {
    courseId: { type: mongoose.Schema.Types.ObjectId, ref: 'Course', required: true },
    title: { type: String, default: 'Course Quiz' },
    passingScore: { type: Number, default: 70 },
    timeLimitMinutes: { type: Number, default: 30 },
    questions: [questionSchema],
    /** True when built from course lessons (can be regenerated). */
    autoGenerated: { type: Boolean, default: false },
    /** curriculum = titles/metadata, video = AI from transcripts */
    generatedFrom: { type: String, enum: ['curriculum', 'video'], default: 'curriculum' },
  },
  { timestamps: true }
);

export const Quiz = mongoose.model('Quiz', quizSchema);
