import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import api from '../../services/api';
import Button from '../../components/Button';

const emptyQuestion = () => ({
  text: '',
  options: ['', '', '', ''],
  correctIndex: 0,
});

export default function InstructorQuiz() {
  const { id } = useParams();
  const [courseTitle, setCourseTitle] = useState('');
  const [lessonCount, setLessonCount] = useState(0);
  const [videoAiAvailable, setVideoAiAvailable] = useState(false);
  const [form, setForm] = useState({
    title: 'Course Quiz',
    passingScore: 70,
    timeLimitMinutes: 15,
    questions: [emptyQuestion()],
  });
  const [msg, setMsg] = useState('');
  const [msgIsError, setMsgIsError] = useState(false);
  const [msgIsWarning, setMsgIsWarning] = useState(false);
  const [autoGenerated, setAutoGenerated] = useState(false);
  const [generatedFrom, setGeneratedFrom] = useState('curriculum');
  const [generating, setGenerating] = useState(false);

  useEffect(() => {
    api.get(`/instructor/courses/${id}`).then((r) => {
      const course = r.data.data;
      setCourseTitle(course.title);
      const count = (course.sections || []).reduce(
        (n, s) => n + (s.lessons?.length || 0),
        0
      );
      setLessonCount(count);
    });
    api.get('/instructor/quiz-ai-status').then((r) => {
      setVideoAiAvailable(!!r.data.data?.videoAiAvailable);
    }).catch(() => {});
    api.get(`/instructor/courses/${id}/quiz`).then((r) => {
      if (r.data.data) {
        setAutoGenerated(!!r.data.data.autoGenerated);
        setGeneratedFrom(r.data.data.generatedFrom || 'curriculum');
        setForm({
          title: r.data.data.title || 'Course Quiz',
          passingScore: r.data.data.passingScore ?? 70,
          timeLimitMinutes: r.data.data.timeLimitMinutes ?? 15,
          questions: r.data.data.questions?.length ? r.data.data.questions : [emptyQuestion()],
        });
      }
    });
  }, [id]);

  const generateFromLessons = async (fromVideo = false) => {
    setMsg('');
    setMsgIsError(false);
    setMsgIsWarning(false);
    setGenerating(true);
    try {
      const { data } = await api.post(
        `/instructor/courses/${id}/quiz/generate`,
        { fromVideo },
        { timeout: fromVideo ? 300000 : 60000 }
      );
      const quiz = data.data;
      setAutoGenerated(true);
      setGeneratedFrom(quiz.generatedFrom || (fromVideo ? 'video' : 'curriculum'));
      setForm({
        title: quiz.title || 'Course Quiz',
        passingScore: quiz.passingScore ?? 70,
        timeLimitMinutes: quiz.timeLimitMinutes ?? 15,
        questions: quiz.questions?.length ? quiz.questions : [emptyQuestion()],
      });
      setMsg(data.message || (fromVideo ? 'Quiz generated from video content.' : 'Quiz generated from lessons.'));
      const warning =
        !!data.message?.includes('quota') ||
        !!data.message?.includes('unavailable') ||
        !!data.message?.includes('instead');
      setMsgIsWarning(warning);
      setMsgIsError(false);
    } catch (err) {
      setMsgIsError(true);
      setMsgIsWarning(false);
      setMsg(err.response?.data?.message || err.message || 'Could not generate quiz');
    } finally {
      setGenerating(false);
    }
  };

  const updateQuestion = (qi, field, value) => {
    setForm((f) => {
      const questions = [...f.questions];
      questions[qi] = { ...questions[qi], [field]: value };
      return { ...f, questions };
    });
  };

  const updateOption = (qi, oi, value) => {
    setForm((f) => {
      const questions = [...f.questions];
      const options = [...questions[qi].options];
      options[oi] = value;
      questions[qi] = { ...questions[qi], options };
      return { ...f, questions };
    });
  };

  const save = async (e) => {
    e.preventDefault();
    setMsg('');
    try {
      await api.post(`/instructor/courses/${id}/quiz`, form);
      setAutoGenerated(false);
      setMsg('Quiz saved.');
    } catch (err) {
      setMsg(err.response?.data?.message || 'Failed to save quiz');
    }
  };

  return (
    <div className="max-w-3xl">
      <Link to="/instructor/courses" className="text-sm text-primary-600">← Back to courses</Link>
      <h1 className="mt-2 text-2xl font-bold">Quiz: {courseTitle}</h1>
      <p className="mt-1 text-sm text-gray-500">
        Quiz auto-builds from lesson titles when you save the course.
        {lessonCount > 0 && ` ${lessonCount} lesson(s) in this course.`}
        {autoGenerated && generatedFrom === 'video' && ' (Generated from video lecture content)'}
        {autoGenerated && generatedFrom !== 'video' && ' (Generated from curriculum metadata)'}
      </p>
      {lessonCount === 0 && (
        <p className="mt-2 rounded-lg border border-amber-200 bg-amber-50 p-3 text-sm text-amber-800">
          Add sections and lessons in the course editor first, then generate the quiz.
        </p>
      )}
      {msg && (
        <p className={`mt-3 text-sm ${
          msgIsError
            ? 'rounded-lg border border-red-200 bg-red-50 p-3 text-red-700'
            : msgIsWarning
              ? 'rounded-lg border border-amber-200 bg-amber-50 p-3 text-amber-800'
              : 'rounded-lg border border-green-200 bg-green-50 p-3 text-green-800'
        }`}>
          {msg}
        </p>
      )}
      <div className="mt-3 flex flex-wrap gap-2">
        <Button
          type="button"
          variant="outline"
          disabled={generating || lessonCount === 0}
          onClick={() => generateFromLessons(false)}
        >
          {generating ? 'Generating…' : 'Regenerate from lessons'}
        </Button>
        <Button
          type="button"
          disabled={generating || lessonCount === 0}
          onClick={() => generateFromLessons(true)}
        >
          {generating ? 'Analyzing videos…' : 'Generate from video content (AI)'}
        </Button>
      </div>
      <p className="mt-2 text-xs text-gray-400">
        {videoAiAvailable
          ? 'Video AI is configured. Transcribes up to 5 lessons (~1–3 min).'
          : 'Video AI: add GEMINI_API_KEY (free) to server/.env — until then, video button builds quiz from lesson titles.'}
      </p>
      <form onSubmit={save} className="mt-6 space-y-6">
        <div className="grid gap-4 sm:grid-cols-3">
          <input
            value={form.title}
            onChange={(e) => setForm({ ...form, title: e.target.value })}
            className="rounded border px-3 py-2"
            placeholder="Quiz title"
          />
          <input
            type="number"
            value={form.passingScore}
            onChange={(e) => setForm({ ...form, passingScore: Number(e.target.value) })}
            className="rounded border px-3 py-2"
            placeholder="Pass %"
          />
          <input
            type="number"
            value={form.timeLimitMinutes}
            onChange={(e) => setForm({ ...form, timeLimitMinutes: Number(e.target.value) })}
            className="rounded border px-3 py-2"
            placeholder="Minutes"
          />
        </div>
        {form.questions.map((q, qi) => (
          <div key={qi} className="rounded-xl border bg-white p-4">
            <p className="text-sm font-medium text-gray-500">Question {qi + 1}</p>
            <input
              value={q.text}
              onChange={(e) => updateQuestion(qi, 'text', e.target.value)}
              className="mt-2 w-full rounded border px-3 py-2"
              required
            />
            <div className="mt-3 space-y-2">
              {q.options.map((opt, oi) => (
                <label key={oi} className="flex items-center gap-2">
                  <input
                    type="radio"
                    name={`correct-${qi}`}
                    checked={q.correctIndex === oi}
                    onChange={() => updateQuestion(qi, 'correctIndex', oi)}
                  />
                  <input
                    value={opt}
                    onChange={(e) => updateOption(qi, oi, e.target.value)}
                    className="flex-1 rounded border px-3 py-1.5 text-sm"
                    required
                  />
                </label>
              ))}
            </div>
          </div>
        ))}
        <Button
          type="button"
          variant="outline"
          onClick={() => setForm((f) => ({ ...f, questions: [...f.questions, emptyQuestion()] }))}
        >
          + Add question
        </Button>
        <Button type="submit">Save quiz</Button>
      </form>
    </div>
  );
}
