import PDFDocument from 'pdfkit';

const BRAND = '#4f46e5';
const NAVY = '#1a2f4a';
const GRAY = '#5c6b7a';
const MUTED = '#94a3b8';

function formatDate(date) {
  if (!date) return '';
  return new Date(date).toLocaleString('en-IN', {
    day: 'numeric',
    month: 'short',
    year: 'numeric',
    hour: '2-digit',
    minute: '2-digit',
  });
}

function safeFilename(value = 'notes') {
  return value
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 80) || 'notes';
}

/**
 * @param {{
 *   studentName: string;
 *   courseTitle: string;
 *   items: Array<{ sectionTitle?: string; lessonTitle: string; notes: string; updatedAt?: Date }>;
 * }} opts
 */
export function generateNotesPDF(opts) {
  const { studentName, courseTitle, items } = opts;

  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 48 });
    const chunks = [];
    doc.on('data', (chunk) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const pageW = doc.page.width;
    const contentW = pageW - 96;

    doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(22).text('LearnHub', 48, 48);
    doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(16).text('Course Notes', 48, 76);
    doc.fillColor(GRAY).font('Helvetica').fontSize(11);
    doc.text(`Student: ${studentName}`, 48, 102);
    doc.text(`Course: ${courseTitle}`, 48, 118);
    doc.text(`Exported: ${formatDate(new Date())}`, 48, 134);

    doc.moveTo(48, 156).lineTo(pageW - 48, 156).strokeColor('#e2e8f0').lineWidth(1).stroke();

    let y = 172;

    items.forEach((item, index) => {
      const blockHeight =
        42 +
        doc.heightOfString(item.lessonTitle, { width: contentW, font: 'Helvetica-Bold', fontSize: 13 }) +
        (item.sectionTitle ? 16 : 0) +
        doc.heightOfString(item.notes, { width: contentW, font: 'Helvetica', fontSize: 11, lineGap: 4 });

      if (y + blockHeight > doc.page.height - 72) {
        doc.addPage();
        y = 48;
      }

      doc.fillColor(BRAND).font('Helvetica-Bold').fontSize(10).text(`Note ${index + 1}`, 48, y);
      y += 16;

      if (item.sectionTitle) {
        doc.fillColor(MUTED).font('Helvetica').fontSize(10).text(item.sectionTitle, 48, y, { width: contentW });
        y += 14;
      }

      doc.fillColor(NAVY).font('Helvetica-Bold').fontSize(13).text(item.lessonTitle, 48, y, { width: contentW });
      y += doc.heightOfString(item.lessonTitle, { width: contentW }) + 4;

      if (item.updatedAt) {
        doc.fillColor(MUTED).font('Helvetica').fontSize(9).text(`Last updated: ${formatDate(item.updatedAt)}`, 48, y);
        y += 14;
      }

      doc.fillColor('#334155').font('Helvetica').fontSize(11).text(item.notes, 48, y, {
        width: contentW,
        lineGap: 4,
      });
      y += doc.heightOfString(item.notes, { width: contentW, lineGap: 4 }) + 18;
    });

    const footerY = doc.page.height - 40;
    doc.fillColor(MUTED).font('Helvetica').fontSize(8).text('Generated by LearnHub', 48, footerY, {
      width: contentW,
      align: 'center',
    });

    doc.end();
  });
}

export function buildNotesFilename(courseTitle, lessonTitle) {
  if (lessonTitle) {
    return `learnhub-notes-${safeFilename(lessonTitle)}.pdf`;
  }
  return `learnhub-notes-${safeFilename(courseTitle)}.pdf`;
}

export function collectCourseNotes(course, enrollment) {
  const notesByLesson = new Map(
    (enrollment.lessonProgress || [])
      .filter((item) => item.notes?.trim())
      .map((item) => [item.lessonId.toString(), item])
  );

  const items = [];
  for (const section of course.sections || []) {
    for (const lesson of section.lessons || []) {
      const progress = notesByLesson.get(lesson._id.toString());
      if (!progress?.notes?.trim()) continue;
      items.push({
        sectionTitle: section.title,
        lessonTitle: lesson.title,
        notes: progress.notes.trim(),
        updatedAt: progress.updatedAt,
      });
    }
  }
  return items;
}

export function findLessonInCourse(course, lessonId) {
  for (const section of course.sections || []) {
    for (const lesson of section.lessons || []) {
      if (lesson._id.toString() === lessonId) {
        return { section, lesson };
      }
    }
  }
  return null;
}
